### ISSUE TITLE
[BUG] On Create Sibling or Child Note, link to child or sibling incorrect

### ISSUE THREAD

**Issue by jamesx4** [Dyldog/luhman-obsidian-plugin#24]
When creating a child or sibling note with _Add titles automatically_ enabled, the link on originating note only contains the Luhman ID, but no title.  The new child or sibling note has the correct <id><separator><title> for the filename, but the link from originating page only has <id>.  So when you click the link on the originating page it takes you to a new note, not the actual child note that was created.

**Comment by Eforen** [comment]
I believe this is a duplicate of #17 and #6 and resolved by #9

**Comment by Eforen** [comment]
For now I am closing this issue as it will be in the upcoming version see the roadmap issue for more information. 
( #19 )

If after we get this update out you still see the problem please feel free to reopen it.

That said this exact issue is why I became one of the mantainers of this project so I will be confirming this is fixed in the upcoming release for sure.

**Comment by Eforen** [comment]
Reopening this issue because its still not fixed just tested current codebase

**Comment by Eforen** [comment]
This should be fixed in PR #31

**Comment by Eforen** [comment]
Resolved by #31
